export const elements = {
    campoInputObjeto: '[name="objeto"]',
    campoInputProcesso: '#processo',
    campoInputOrgao: '#orgao',
    botaoBuscarProcesso: '.btn-pesquisa-p',
    botaoBuscaAvancada: 'a.busca-av',
    dropdownStatus: '#Status',
    dropdownModalidade: '#Modalidade',
    dropdownRealizacao: '#Realizacao',
    dropdownJulgamento: '#julgamento',
    campoPeriodo: '.busca-av-block > :nth-child(5)',
    dataDoProcesso: '.lista-processos',
    dropdownUf: '[name="UF"]',
    dropdownMunicipio: '#municipios',
    resultadoObjetoProcesso: '.item',
    resultadoProcessos: 'span[style*="color: rgb(0, 96, 108)"]',
    resultadoOrgao: 'div.item',
    resultadoBuscaAvancada: '.lista-processos',
};