export const elements = {
    campoInputObjeto: '#objeto',
    campoInputProcesso: '#processo',
    campoInputOrgao: '#orgao',
    botaoBuscarProcesso: '.btn-pesquisa-p.second',
    botaoBuscaAvancada: 'a.busca-av',
    dropdownStatus: '#Status',
    dropdownModalidade: '#Modalidade',
    dropdownRealizacao: '#Realizacao',
    dropdownJulgamento: '#julgamento',
    campoPeriodo: '#periodo',
    dataDoProcesso: 'section.resultado-pesquisa table tbody tr',
    dropdownUf: '#UF',
    dropdownMunicipio: '#municipios',
    resultadoObjetoProcesso: 'a[href*="processos"]',
    resultadoProcessos: 'span[style*="color: rgb(0, 96, 108)"]',
    resultadoOrgao: 'div.item',
    resultadoBuscaAvancada: '.numeros-resultados span',
};